import bcrypt from "bcryptjs";

export const data = {
  users: [
    {
      name: "Dima",
      email: "lebedev.023046@gmail.com",
      password: bcrypt.hashSync("12345678"),
      isAdmin: true,
    },
    {
      name: "Artyom",
      email: "arleb@gmail.com",
      password: bcrypt.hashSync("87654321"),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "suit",
      size: [42, 44, 46, 48],
      color: "blue",
      price: 178,
      image: "/goodImgs/blue_hoodie.jpg",
      slug: "blue_hoodie",
      year: 2022,
      rating: 0,
      countInStock: 28,
    },
    {
      name: "t-shirt",
      size: [42, 44, 46, 48, 50, 52],
      color: "yellow",
      price: 69,
      image: "/goodImgs/yellow_t-shirt.jpg",
      slug: "yellow_t-shirt",
      year: 2022,
      rating: 0,
      countInStock: 20,
    },
    {
      name: "sweatshirt",
      size: [46, 48, 50, 52],
      color: "gray",
      price: 89,
      image: "/goodImgs/gray_sweatshirt.jpg",
      slug: "gray_sweatshirt",
      year: 2021,
      rating: 0,
      countInStock: 12,
    },
    {
      name: "summer suit",
      size: [42, 44, 46],
      color: "pink",
      price: 138,
      image: "/goodImgs/pink_summer_suit.jpg",
      slug: "pink_summer_suit",
      year: 2021,
      rating: 0,
      countInStock: 40,
    },
    {
      name: "t-shirt",
      size: [42, 44, 46, 48, 50, 52],
      color: "blue",
      price: 69,
      image: "/goodImgs/blue_t-shirt.jpg",
      slug: "blue_t-shirt",
      year: 2022,
      rating: 0,
      countInStock: 33,
    },
    {
      name: "suit",
      size: [42, 46, 48, 50, 52],
      color: "white",
      price: 178,
      image: "/goodImgs/white_hoodie.jpg",
      slug: "white_hoodie",
      year: 2022,
      rating: 0,
      countInStock: 29,
    },
    {
      name: "suit",
      size: [42, 46, 52],
      color: "gray",
      price: 178,
      image: "/goodImgs/gray_hoodie.jpg",
      slug: "gray_hoodie",
      year: 2022,
      rating: 0,
      countInStock: 18,
    },
    {
      name: "summer suit",
      size: [42, 44, 46],
      color: "yellow",
      price: 138,
      image: "/goodImgs/yellow_summer_suit.jpg",
      slug: "yellow_summer_suit",
      year: 2021,
      rating: 0,
      countInStock: 11,
    },
    {
      name: "palazzo",
      size: [42, 44, 50, 52],
      color: "black",
      price: 148,
      image: "/goodImgs/black_palazzo.jpg",
      slug: "black_palazzo",
      year: 2021,
      rating: 0,
      countInStock: 7,
    },
    {
      name: "palazzo",
      size: [42, 50],
      color: "brown",
      price: 148,
      image: "/goodImgs/brown_palazzo.jpg",
      slug: "brown_palazzo",
      year: 2020,
      rating: 0,
      countInStock: 19,
    },
    {
      name: "suit",
      size: [42, 44, 48, 52],
      color: "brown",
      price: 178,
      image: "/goodImgs/brown_hoodie.jpg",
      slug: "brown_hoodie",
      year: 2022,
      rating: 0,
      countInStock: 25,
    },
  ],
};
