export const data = {
  products: [
    {
      id: "1",
      name: "suit",
      size: [42, 44, 46, 48],
      color: "blue",
      price: 178,
      img: "/goodImgs/blue_hoodie.jpg",
      slug: "blue_hoodie",
      year: 2022,
      popular: true,
      brand: "Mazy",
      quantity: 28,
    },
    {
      id: "2",
      name: "t-shirt",
      size: [42, 44, 46, 48, 50, 52],
      color: "yellow",
      price: 69,
      img: "/goodImgs/yellow_t-shirt.jpg",
      slug: "yellow_t-shirt",
      year: 2022,
      popular: true,
      brand: "Mazy",
      quantity: 20,
    },
    {
      id: "3",
      name: "sweatshirt",
      size: [46, 48, 50, 52],
      color: "gray",
      price: 89,
      collection: "summer night",
      img: "/goodImgs/gray_sweatshirt.jpg",
      slug: "gray_sweatshirt",
      year: 2021,
      popular: true,
      brand: "Mazy",
      quantity: 12,
    },
    {
      id: "4",
      name: "summer suit",
      size: [42, 44, 46],
      color: "pink",
      price: 138,
      collection: "summer night",
      img: "/goodImgs/pink_summer_suit.jpg",
      slug: "pink_summer_suit",
      year: 2021,
      popular: true,
      brand: "Mazy",
      quantity: 40,
    },
    {
      id: "5",
      name: "t-shirt",
      size: [42, 44, 46, 48, 50, 52],
      color: "blue",
      price: 69,
      img: "/goodImgs/blue_t-shirt.jpg",
      slug: "blue_t-shirt",
      year: 2022,
      popular: false,
      brand: "Mazy",
      quantity: 33,
    },
    {
      id: "6",
      name: "suit",
      size: [42, 46, 48, 50, 52],
      color: "white",
      price: 178,
      img: "/goodImgs/white_hoodie.jpg",
      slug: "white_hoodie",
      year: 2022,
      popular: false,
      brand: "Mazy",
      quantity: 29,
    },
    {
      id: "7",
      name: "suit",
      size: [42, 46, 52],
      color: "gray",
      price: 178,
      img: "/goodImgs/gray_hoodie.jpg",
      slug: "gray_hoodie",
      year: 2022,
      popular: false,
      brand: "Mazy",
      quantity: 18,
    },
    {
      id: "8",
      name: "summer suit",
      size: [42, 44, 46],
      color: "yellow",
      price: 138,
      img: "/goodImgs/yellow_summer_suit.jpg",
      slug: "yellow_summer_suit",
      year: 2021,
      popular: true,
      brand: "Mazy",
      quantity: 11,
    },
    {
      id: "9",
      name: "palazzo",
      size: [42, 44, 50, 52],
      color: "black",
      price: 148,
      img: "/goodImgs/black_palazzo.jpg",
      slug: "black_palazzo",
      year: 2021,
      popular: true,
      brand: "Mazy",
      quantity: 7,
    },
    {
      id: "10",
      name: "palazzo",
      size: [42, 50],
      color: "brown",
      price: 148,
      img: "/goodImgs/brown_palazzo.jpg",
      slug: "brown_palazzo",
      year: 2020,
      popular: true,
      brand: "Mazy",
      quantity: 19,
    },
    {
      id: "11",
      name: "suit",
      size: [42, 44, 48, 52],
      color: "brown",
      price: 178,
      img: "/goodImgs/brown_hoodie.jpg",
      slug: "brown_hoodie",
      year: 2022,
      popular: true,
      brand: "Mazy",
      quantity: 25,
    },
  ],
};
